### ISSUE TITLE
Missing example pdfs

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-v0.2-paper#16]
It looks like `examples/code_constants.pdf` and `examples/code_quantities.pdf` aren't in the repo.  I can build them locally with `examples/process.py`, but the output files are different from the other pdfs, so probably whoever made them initially should re-make them and add them to the repo (@astrofrog, I think?).

**Comment by astrofrog** [comment]
Will do - thanks for pointing this out!

**Comment by astrofrog** [comment]
Fixed in dbc871082ee996d292e2f4b3ba69e020a405f59f
